---
AWSTemplateFormatVersion: '2010-09-09'
Description: Test API Gateway to invoke Lambda
Resources:
  TestApiGatewayLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: arn:aws:iam::674616069637:role/LamdaS3
      Code:
        S3Bucket: pk-poc-templates
        S3Key: demo-1.0.0.jar
      Handler: com.amazonaws.lambda.demo.LamdaStreamHandler::handleRequest
      Runtime: java8
      Timeout: 25
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
        Fn::GetAtt:
          - TestApiGatewayLambda
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: ApiGatewayGetMethod
            - "/*"
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
        - RestApi
        - RootResourceId
      PathPart: idm
      RestApiId:
        Ref: RestApi
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: LambdaGate2
  ApiGatewayGetMethod:
    DependsOn: TestApiGatewayLambda
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: 'false'
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Credentials: arn:aws:iam::674616069637:role/LamdaS3
        IntegrationResponses:
        - StatusCode: '200'
        RequestTemplates:
          application/json:
            Fn::Join:
              - ''
              - - "{"
                - '  "a": "$input.params(''operand1'')"'
                - ","
                - '  "b": "$input.params(''operand2'')"'
                - ","
                - '  "op": "$input.params(''operator'')"'
                - "}"
        Type: AWS
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TestApiGatewayLambda.Arn}/invocations
      MethodResponses:
      - StatusCode: '200'
      RequestParameters:
        method.request.querystring.operand1: true
        method.request.querystring.operand2: true
        method.request.querystring.operator: true
      ResourceId:
        Ref: ApiGatewayResource
      RestApiId:
        Ref: RestApi
